"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { ArrowDown, ArrowRight, Check, ChevronRight, Circle, Clock3, Coffee, Network, Send, TerminalSquare, UserRound } from "lucide-react";

const roles = {
  ENGINEER:{label:"エンジニア",title:"仕組みを、動くものにする。",fit:"曖昧な問いを分解し、手を動かしながら考えたい人",day:["09:30 PRレビュー","11:00 実装","14:00 設計相談","16:00 集中開発"],code:["const idea = observe(problem);","const prototype = build(idea);","return learn(prototype);"]},
  DESIGNER:{label:"デザイナー",title:"まだない使い方を、形にする。",fit:"見た目だけでなく、体験の理由まで設計したい人",day:["09:30 リサーチ","11:00 プロトタイプ","14:00 ユーザーテスト","16:30 UI改善"],code:["FRAME / ONBOARDING","GRID  12 COL","PROTOTYPE  ● CONNECTED"]},
  SALES:{label:"セールス",title:"売る前に、課題を見つける。",fit:"相手の言葉になっていない課題を、一緒に整理したい人",day:["09:00 商談準備","11:00 ヒアリング","14:30 提案設計","17:00 チーム共有"],code:["ACCOUNT / NEW","NEED  ● DISCOVERED","NEXT  PROPOSAL REVIEW"]},
  MARKETING:{label:"マーケティング",title:"数字の奥の、人を読む。",fit:"仮説と検証を往復し、伝わり方を改善したい人",day:["09:30 数値確認","11:00 企画","14:00 取材","16:30 分析"],code:["VISITORS  24,810  ↑12%","SIGNUPS   1,284  ↑08%","INSIGHT   STORY / B"]},
  CORPORATE:{label:"コーポレート",title:"挑戦が続く、土台をつくる。",fit:"ルールと人の両方を見ながら、組織を前に進めたい人",day:["09:30 入社準備","11:00 制度設計","14:00 1on1","16:30 経営会議"],code:["PEOPLE OPS / ACTIVE","POLICY  ● REVIEW","ONBOARDING  06/08"]},
};
const people=[{name:"高橋 海",role:"Designer",status:"新規事業の体験設計を担当しています。正解がないから、観察から始めます。"},{name:"石井 蓮",role:"Engineer",status:"コードを書かない日は少ないです。でも、先にチームで問いを揃えます。"},{name:"佐藤 澪",role:"Sales",status:"営業というより、顧客と一緒に課題の輪郭をつくる仕事です。"}];
const careers={SPECIALIST:"技術や表現を深く掘り、難しい問いに名前をつける。肩書きより、専門性でチームを前へ。",MANAGER:"個人の強みをつなぎ、チームの意思決定を良くする。管理ではなく、前進を設計する。","NEW BUSINESS":"顧客のまだ言葉にならない課題から、新しい事業の最初の1ページをつくる。"};

export default function Home(){
 const[role,setRole]=useState<keyof typeof roles>("ENGINEER");const[person,setPerson]=useState(0);const[career,setCareer]=useState<keyof typeof careers>("SPECIALIST");const[sent,setSent]=useState(false);const[progress,setProgress]=useState(0);
 useEffect(()=>{const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;setProgress(max>0?(scrollY/max)*100:0)};addEventListener("scroll",update,{passive:true});update();return()=>removeEventListener("scroll",update)},[]);
 function submit(e:{preventDefault():void}){e.preventDefault();setSent(true)} const activeRole=roles[role];
 return <main>
  <div className="boot" aria-hidden="true"><span>NEXUS_OS / CONNECTING</span><i/></div><div className="scroll-progress" style={{width:`${progress}%`}}/>
  <nav className="topbar" aria-label="メインナビゲーション"><a href="#top" className="brand"><span>N</span>NEXUS Inc.</a><div className="nav-links"><a href="#story">STORY</a><a href="#roles">ROLES</a><a href="#jobs">JOBS</a></div><a href="#entry" className="entry-link">ENTRY <ArrowRight size={15}/></a></nav>
  <section className="hero" id="top"><div className="hero-grid" aria-hidden="true"/><div className="hero-time"><span>2026.04.01</span><strong>09:02</strong></div><div className="hero-copy"><p className="system-line"><span>●</span> WELCOME TO NEXUS.<i/></p><h1>今日から、<br/>ここで働く。</h1></div><a className="scroll-cue" href="#story"><ArrowDown size={16}/> SCROLL TO START YOUR FIRST DAY</a><div className="hero-status"><span>EMPLOYEE_ID / 042</span><span>STATUS / FIRST_DAY</span></div></section>
  <section className="day-section" id="story"><SectionRail day="DAY 001" time="09:02" label="出社"/><div className="split documentary"><figure className="photo-frame"><Image src="/images/day-001.webp" width={1536} height={1024} priority alt="新人社員が先輩とパソコンを確認する自然なオフィス風景"/><figcaption>APR 01 / ONBOARDING / PHOTO_001</figcaption></figure><div className="chat-panel"><div className="panel-head"><span># general</span><span>32 members</span></div><Chat name="NEXUS BOT" time="09:02" text="おはようございます。今日から新しいメンバーが加わりました。" bot/><Chat name="高橋 海" time="09:03" text="席は窓側です。わからないことは、そのままにしないでください。"/><Chat name="石井 蓮" time="09:04" text="まずはPCの設定から。一緒にやりましょう。"/><div className="chat-input">メッセージを入力… <Send size={15}/></div></div></div></section>
  <section className="day-section project-section"><SectionRail day="DAY 001" time="10:15" label="最初の仕事"/><div className="project-board"><div className="project-title"><div><span>PROJECT 001</span><h2>新サービス LP改善</h2></div><div className="project-owner"><UserRound size={18}/> OWNER / TEAM A</div></div><div className="kanban"><Task done title="デザイン確認" tag="DESIGN"/><Task done title="競合調査" tag="RESEARCH"/><Task active title="UI案作成" tag="DESIGN"/><Task title="実装" tag="ENGINEERING"/><Task title="公開" tag="RELEASE"/></div><div className="board-footer"><span>2 / 5 COMPLETED</span><div><i style={{width:"40%"}}/></div><span>DUE / APR 11</span></div></div></section>
  <section className="day-section lunch-section"><SectionRail day="DAY 001" time="12:34" label="LUNCH" orange/><div className="lunch-layout"><div className="lunch-copy"><Coffee size={31}/><h2>仕事の話を、<br/>しない時間もある。</h2><p>近所の定食屋。昨日見た映画の話。午後の予定は、戻ってから考える。</p></div><figure className="photo-frame"><Image src="/images/lunch.webp" width={1536} height={1024} loading="lazy" alt="同僚たちが自然に昼食を囲む風景"/><figcaption>12:34 / OFF THE CLOCK</figcaption></figure></div></section>
  <section className="error-section"><div className="error-stamp">ERROR / 15:42</div><div className="error-copy"><span>PROJECT_001 / REVIEW_FAILED</span><h2>最初から、<br/>うまくはいかない。</h2></div><ol className="recovery-flow"><li><b>01</b><span>提案したデザインが<br/>全部ボツになった。</span></li><li><b>02</b><span>もう一度、ユーザーを<br/>観察し直した。</span></li><li><b>03</b><span>先輩に相談した。<br/>答えではなく問いをもらった。</span></li><li className="recovered"><b>04</b><span>次の日、通った。<br/><strong>RECOVERED</strong></span></li></ol></section>
  <section className="complete-section"><div><span>18:21 / SYNC COMPLETE</span><strong>8<span>/8</span></strong><p>TASKS COMPLETED</p></div><h2>入社1日目、<br/>おつかれさまでした。</h2></section>
  <section className="time-tunnel" aria-label="時間の経過"><span>DAY 030</span><span>DAY 180</span><span>YEAR 01</span><span>YEAR 03</span><strong>YEAR 05</strong></section>
  <section className="growth-section"><div className="section-kicker">06 / 6 MONTHS</div><h2>半年前には、<br/>できなかったこと。</h2><div className="growth-compare"><div><span>DAY 001</span><Task title="顧客との打ち合わせ" tag="PENDING"/><Task title="プロジェクト設計" tag="PENDING"/><Task title="プレゼン" tag="PENDING"/></div><ArrowRight className="growth-arrow"/><div className="after"><span>DAY 180</span><Task done title="顧客との打ち合わせ" tag="DONE"/><Task done title="プロジェクト設計" tag="DONE"/><Task done title="プレゼン" tag="DONE"/></div></div></section>
  <section className="network-section"><div className="section-kicker">07 / YEAR 01</div><h2>今度は、自分が<br/>任される番。</h2><div className="network-map"><div className="node owner"><Network size={20}/><b>PROJECT OWNER</b><span>YOU</span></div>{["DESIGN","ENGINEERING","MARKETING","CLIENT"].map((x,i)=><div key={x} className={`node node-${i}`}><Circle size={10} fill="currentColor"/>{x}</div>)}</div></section>
  <section className="people-section"><div className="section-kicker">08 / PEOPLE.DM</div><h2>肩書きではなく、<br/>話してみる。</h2><div className="dm-shell"><div className="dm-list"><div className="dm-search">DMを検索</div>{people.map((p,i)=><button key={p.name} onClick={()=>setPerson(i)} className={person===i?"active":""}><span>{p.name.slice(0,1)}</span><div><b>{p.name}</b><small>{p.role}</small></div><i/></button>)}</div><div className="dm-chat"><div className="panel-head"><span>{people[person].name}</span><span>● ACTIVE</span></div><div className="bubble">最近は、どんな仕事をしていますか？</div><div className="bubble reply"><b>{people[person].name}</b>{people[person].status}</div><div className="typing">メッセージを入力…</div></div></div></section>
  <section className="log-section"><div className="log-head"><span>09 / COMPANY.log</span><span>DEMO DATA / 2026</span></div><h2>会社を、ログで見る。</h2><div className="logs">{[["EMPLOYEES","128","+18"],["AVG_AGE","32.4","YEARS"],["REMOTE","63","%"],["PAID_LEAVE","78","%"],["OVERTIME","14.2","H/MONTH"],["PARENTAL_LEAVE","92","%"]].map(([a,b,c],i)=><div key={a} style={{"--delay":`${i*.12}s`} as React.CSSProperties}><span>&gt; LOAD {a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><p className="demo-note">※ NEXUS Inc. は架空企業です。掲載数値はポートフォリオ用のデモデータです。</p></section>
  <section className={`roles-section role-${role.toLowerCase()}`} id="roles"><div className="section-kicker">10 / CHOOSE YOUR ROLE</div><div className="role-tabs" role="tablist">{(Object.keys(roles) as (keyof typeof roles)[]).map(x=><button role="tab" aria-selected={role===x} key={x} onClick={()=>setRole(x)}>{x}</button>)}</div><div className="role-workspace"><div className="role-copy"><span>{activeRole.label}</span><h2>{activeRole.title}</h2><p><b>向いている人</b>{activeRole.fit}</p><ul>{activeRole.day.map(x=><li key={x}><Clock3 size={15}/>{x}</li>)}</ul></div><div className="role-screen"><div className="screen-top"><i/><i/><i/><span>{role.toLowerCase()}.workspace</span></div><div className="screen-content"><aside>01<br/>02<br/>03<br/>04<br/>05</aside><pre>{activeRole.code.join("\n\n")}</pre></div></div></div></section>
  <section className="week-section"><div><div className="section-kicker">11 / A WEEK</div><h2>制度ではなく、<br/>働き方を見せる。</h2></div><div className="calendar">{[["MON","MTG / DESIGN","OFFICE"],["TUE","REMOTE / PROJECT","HOME"],["WED","CLIENT MTG","SHIBUYA"],["THU","FOCUS DAY","NO MTG"],["FRI","REVIEW / 18:30 DINNER","OFFICE"]].map((x,i)=><div key={x[0]} className={i===3?"focus":""}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></div>)}</div></section>
  <section className="benefits-section"><div className="section-kicker">12 / BENEFITS.UI</div><h2>働くための、設定。</h2><div className="benefit-ui"><div className="payslip"><span>PAYSLIP / MONTHLY</span><p>BASE SALARY <b>¥340,000</b></p><p>HOUSING <b>+ ¥20,000</b></p><p>COMMUTE <b>ACTUAL</b></p></div><div className="settings">{[["REMOTE WORK","ON"],["PC SELECT","ON"],["FLEX TIME","ON"],["BOOK BUDGET","ON"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><i/></p>)}</div><div className="leave"><span>PAID LEAVE</span><strong>18</strong><small>DAYS AVAILABLE</small><button>REQUEST →</button></div></div><p className="demo-note">※ 制度・金額・条件は架空の設定です。</p></section>
  <section className="year3-section"><div className="year3-copy"><div className="section-kicker">13 / YEAR 03</div><h2>3年前、<br/>教えてもらっていた。<br/><em>今、教える側になった。</em></h2><p>最初の日にもらった問いを、今度は新しい誰かへ。</p></div><figure className="photo-frame"><Image src="/images/year-03.webp" width={1536} height={1024} loading="lazy" alt="3年目の社員が新入社員に仕事を教える自然な風景"/><figcaption>2029.04.01 / ONBOARDING / MENTOR</figcaption></figure></section>
  <section className="career-section"><div className="section-kicker">14 / YEAR 05</div><h2>一本道じゃない。<br/>昇進だけが、正解じゃない。</h2><div className="career-branches">{(Object.keys(careers) as (keyof typeof careers)[]).map((x,i)=><button key={x} onClick={()=>setCareer(x)} className={career===x?"active":""}><span>0{i+1}</span>{x}<ChevronRight size={18}/></button>)}</div><div className="career-result"><span>SELECTED PATH / {career}</span><p>{careers[career]}</p></div></section>
  <section className="jobs-section" id="jobs"><div className="section-kicker">15 / OPEN POSITIONS</div><h2>募集要項</h2><div className="job-table"><dl><dt>募集職種</dt><dd>エンジニア / デザイナー / セールス / マーケティング / コーポレート</dd><dt>仕事内容</dt><dd>デジタルプロダクト・AIサービスの企画、設計、開発、顧客支援</dd><dt>給与</dt><dd>年収 450万円〜800万円（経験・能力を考慮）</dd><dt>勤務地</dt><dd>東京都渋谷区 / リモートワーク可（週2日目安の出社）</dd><dt>勤務時間</dt><dd>フレックスタイム制 / コアタイム 11:00–15:00</dd><dt>休日</dt><dd>完全週休2日、祝日、年次有給休暇、特別休暇</dd><dt>選考フロー</dt><dd>書類確認 → カジュアル面談 → 面接2回 → オファー</dd></dl></div><p className="demo-note">※ 本サイトおよび募集要項はポートフォリオ用の架空コンテンツです。実際の募集は行っていません。</p></section>
  <section className="final-section" id="entry"><div className="final-date"><span>2031.04.01</span><strong>09:02</strong></div><div className="final-copy"><span>ENTRY / CREATE ACCOUNT</span><h2>5年後のあなたを、<br/>ここから始めよう。</h2></div><form onSubmit={submit} className="entry-form"><label>NAME<input required name="name" placeholder="山田 花"/></label><label>EMAIL<input required name="email" type="email" placeholder="you@example.com"/></label><label>ROLE<select name="role" defaultValue=""><option value="" disabled>選択してください</option>{Object.entries(roles).map(([k,v])=><option key={k}>{v.label}</option>)}</select></label><button type="submit">{sent?<><Check size={19}/> DEMO ENTRY COMPLETE</>:<>YOUR NEXT DAY STARTS HERE <ArrowRight size={19}/></>}</button></form><p className="portfolio-note">PORTFOLIO DEMO — このフォームは送信されません。</p></section>
  <footer><span>NEXUS Inc. / FICTIONAL COMPANY</span><span>© 2026 PORTFOLIO DEMO</span><a href="#top">BACK TO 2026 ↑</a></footer>
 </main>
}
function SectionRail({day,time,label,orange=false}:{day:string;time:string;label:string;orange?:boolean}){return <header className={`section-rail ${orange?"orange":""}`}><span>{day}</span><strong>{time}</strong><b>{label}</b><i/></header>}
function Chat({name,time,text,bot=false}:{name:string;time:string;text:string;bot?:boolean}){return <div className="chat"><div className={bot?"avatar bot":"avatar"}>{bot?<TerminalSquare size={16}/>:name.slice(0,1)}</div><p><b>{name}</b><small>{time}</small><span>{text}</span></p></div>}
function Task({title,tag,done=false,active=false}:{title:string;tag:string;done?:boolean;active?:boolean}){return <div className={`task ${done?"done":""} ${active?"active":""}`}><span className="check">{done?<Check size={15}/>:active?<span className="pulse"/>:<Circle size={13}/>}</span><b>{title}</b><small>{tag}</small><ChevronRight size={15}/></div>}
